import java.util.List;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Assignment1 {
    public List<Transaction> validate(List<Transaction> block) {
        return null;
    }
}
