/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import static org.junit.Assert.*;

public class Assignment1Test {
    @Test public void testSomeLibraryMethod() {
        Assignment1 classUnderTest = new Assignment1();
        assertNotNull("someLibraryMethod should return 'true'", classUnderTest.validate(null));
    }
}
